USE ibm_ds_class;

CREATE TABLE PETSALE (
    ID INTEGER NOT NULL,
    PET CHAR(20),
    SALEPRICE DECIMAL(6 , 2 ),
    PROFIT DECIMAL(6 , 2 ),
    SALEDATE DATE
);

CREATE TABLE PET (
    ID INTEGER NOT NULL,
    ANIMAL VARCHAR(20),
    QUANTITY INTEGER
);

INSERT INTO PETSALE 
VALUES 
    (1, 'Cat', 450.09, 100.47, '2018-05-29'),
    (2, 'Dog', 666.66, 150.60, '2018-06-01'),
    (3, 'Parrot', 50.00, 8.9, '2018-06-04'),
    (4, 'Hamster', 60.60, 9.9, '2018-06-11'),
    (5, 'Goldfish', 48.48, 8.8, '2018-06-14');

INSERT INTO PET
VALUES
    (1, 'Cat', 3),
    (2, 'Dog', 4),
    (3, 'Hamster', 2);
    
SELECT * FROM PETSALE;

SELECT * FROM PET;

ALTER TABLE PETSALE
ADD COLUMN QUANTITY INTEGER;

SELECT * FROM PETSALE;


SET SQL_SAFE_UPDATES = 0;
UPDATE PETSALE
SET QUANTITY = CASE
	WHEN ID = 1 THEN 9
    WHEN ID = 2 THEN 3
    WHEN ID = 3 THEN 2
    WHEN ID = 4 THEN 6
    WHEN ID = 5 THEN 24
END
WHERE ID IN (1,2,3,4,5);
SET SQL_SAFE_UPDATES = 1;

SELECT * FROM PETSALE;

# ---- Delete a column ----
ALTER TABLE PETSALE
DROP COLUMN PROFIT;

SELECT * FROM PETSALE;

# ---- Modify a column ----
ALTER TABLE PETSALE
MODIFY PET VARCHAR(20);
SELECT * FROM PETSALE;

# ---- Rename a column ----
ALTER TABLE PETSALE 
CHANGE COLUMN PET ANIMAL VARCHAR(20);

SELECT * FROM PETSALE;

# ---- Trancate Statements ----

TRUNCATE TABLE PET;
SELECT * FROM PET;






    